name: Publish Docker image
on:
  push:
    branches:
      - main
  schedule:
    - cron: 10 * * * *
  workflow_dispatch: {}

jobs:
  docker_hub:
    name: Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Get repo name
        id: repoName
        run: echo "::set-output name=reponame::$(echo ${{github.repository}} | cut -d '/' -f 2)"
      - name: Get short SHA
        id: sha
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer
          push: true
          file: ./.devcontainer/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repoName.outputs.reponame }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repoName.outputs.reponame }}:${{ steps.sha.outputs.sha7 }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
